## 💚Estadística 

In [2]:
import pandas as pd
import tensorflow as tf

In [7]:
fashion_mnist = tf.keras.datasets.fashion_mnist
(imagenes, categorias) = fashion_mnist.load_data()[0]

In [8]:
imagenes.shape

(60000, 28, 28)

In [12]:
imagenes[0].shape , categorias[0]

((28, 28), 9)

## ⭐Conceptos de estadística

Tipos de datos:

 * Númericos:  Continuos, porcentajes y enteros
 
 * Categóricos: categórias ordinales(fechas) y clases sin sentido ordinal

## ⭐Variables determinísticas y Variables aleatorias

- Determinista : valor puntual
- Incertidumbre
- Aleatoriedad : valores que cambian en un rango


In [14]:
import numpy as np
import datetime 
from datetime import date

In [15]:
type('1')

str

In [16]:
type(0)

int

In [17]:
type(1.2)

float

In [18]:
type(1.1 + 1)

float

In [20]:
type('1.1'+'1')

str

In [21]:
list_1=[ '1', 0 , [1,2]]

In [22]:
list_1[0]

'1'

In [24]:
list_1[2][1]

2

Hagamos un experimento aleatorio del lanzamiento de un dado

In [25]:
universo =['cara', 'sello']

In [26]:
# numeros casos favores/ numero de casos totales
p_cara = 1/2

In [48]:
from scipy.stats import bernoulli

bernoulli.rvs(p =p_cara)

universo[bernoulli.rvs(p =p_cara)]

bernoulli.rvs(p=p_cara, size = 10)

array([0, 0, 1, 0, 0, 0, 1, 0, 0, 0])

In [49]:
sum(bernoulli.rvs(p = p_cara, size = 10))

8

In [45]:
from scipy.stats import binom

In [52]:
#binom.rvs(p=p_cara , n = 10)

#Distribución de probabilidad, algunos valores son mas probables que otros
binom.rvs(p=p_cara , n = 10, size=100)

array([ 5,  4,  3,  6,  3,  2,  6,  4,  5,  7,  5,  4,  6,  4,  3,  6,  6,
        6,  3,  5,  6,  2,  4,  5,  5,  5,  7,  4,  9,  3,  6,  5,  6,  7,
        6,  3,  5,  2,  2,  4,  5,  6,  6,  5,  4,  6,  2,  4,  7,  7,  3,
        7,  5,  4,  6,  6,  5,  6,  6,  6,  3,  3,  4,  5,  3,  5,  5,  7,
        5,  7,  7,  4,  7,  5,  5,  6,  7,  6,  4,  6,  6,  5,  5,  5,  6,
        3,  5,  6,  5,  8,  6,  5,  4,  5,  5,  6,  5, 10,  6,  5])

In [61]:
import pandas as pd
pd.Series(binom.rvs(p=p_cara, n = 10, size=100)).value_counts()/ 100

6    0.29
4    0.21
5    0.19
3    0.14
7    0.09
2    0.04
8    0.03
1    0.01
dtype: float64

## ⭐Medidas de tendencia central

* Media io primedio geométrico y aritmético
* Mediana
* Moda


Criterios de aplicación: Segín el tipo de variables y susceptibilidad a los valores extremos

In [26]:
import pandas as pd
import scipy
import scipy.stats
import numpy as np

In [8]:
df = pd.read_csv('D:/Users/luzbog/Desktop/bicicletas-compartidas.csv')

In [9]:
df.head()

fecha  bicis-compartidas  temp-obs  sens-temp    hum  viento  \
0  2015-01-04 00:00:00                182       3.0        2.0   93.0     6.0   
1  2015-01-04 01:00:00                138       3.0        2.5   93.0     5.0   
2  2015-01-04 02:00:00                134       2.5        2.5   96.5     0.0   
3  2015-01-04 03:00:00                 72       2.0        2.0  100.0     0.0   
4  2015-01-04 04:00:00                 47       2.0        0.0   93.0     6.5   

   codigo-clima  festivo  findesemana  cuartil-ano  
0           3.0      0.0          1.0          3.0  
1           1.0      0.0          1.0          3.0  
2           1.0      0.0          1.0          3.0  
3           1.0      0.0          1.0          3.0  
4           1.0      0.0          1.0          3.0

In [10]:
df.columns

Index(['fecha', 'bicis-compartidas', 'temp-obs', 'sens-temp', 'hum', 'viento',
       'codigo-clima', 'festivo', 'findesemana', 'cuartil-ano'],
      dtype='object')

In [11]:
y = df['bicis-compartidas'].values

In [14]:
y = np.where(y == 0,1 , y)

In [15]:
y

array([182, 138, 134, ..., 337, 224, 139], dtype=int64)

In [16]:
np.min(y)

1

In [17]:
np.max(y)

7860

In [18]:
#Medida de tendencia central, el promedio
#sum(yi)/n

np.mean(y)

1143.1016997817849

In [19]:
np.sum(y)/len(y)

1143.1016997817849

In [23]:
#media geometrica

scipy.stats.mstats.hmean(y)

241.65180305136826

In [28]:
np.median(y)

844.0

In [29]:
#moda = valor de y con la máxima frecuencia

moda = np.nan
valores, conteo_valores = np.unique(y, return_counts = True)
pos = np.argmax(conteo_valores)
moda =valores[pos]

In [30]:
moda

46

In [31]:
#desviación estandar, que tanto se alejan del promedio
np.std(y)

1085.0768508213835

Revisiones 

In [32]:
y_alterado = y.copy()

In [33]:
y_alterado[y_alterado == max(y_alterado)]= 1000000

In [34]:
print(np.mean(y_alterado))

1200.075399104169
